package com.timecat.component.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.timecat.component.greendao.model.AppInfo;
import com.timecat.component.greendao.model.TimeBlock;
import com.timecat.component.greendao.model.TimeBlockTemplate;

import com.timecat.component.greendao.dao.AppInfoDao;
import com.timecat.component.greendao.dao.TimeBlockDao;
import com.timecat.component.greendao.dao.TimeBlockTemplateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInfoDaoConfig;
    private final DaoConfig timeBlockDaoConfig;
    private final DaoConfig timeBlockTemplateDaoConfig;

    private final AppInfoDao appInfoDao;
    private final TimeBlockDao timeBlockDao;
    private final TimeBlockTemplateDao timeBlockTemplateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInfoDaoConfig = daoConfigMap.get(AppInfoDao.class).clone();
        appInfoDaoConfig.initIdentityScope(type);

        timeBlockDaoConfig = daoConfigMap.get(TimeBlockDao.class).clone();
        timeBlockDaoConfig.initIdentityScope(type);

        timeBlockTemplateDaoConfig = daoConfigMap.get(TimeBlockTemplateDao.class).clone();
        timeBlockTemplateDaoConfig.initIdentityScope(type);

        appInfoDao = new AppInfoDao(appInfoDaoConfig, this);
        timeBlockDao = new TimeBlockDao(timeBlockDaoConfig, this);
        timeBlockTemplateDao = new TimeBlockTemplateDao(timeBlockTemplateDaoConfig, this);

        registerDao(AppInfo.class, appInfoDao);
        registerDao(TimeBlock.class, timeBlockDao);
        registerDao(TimeBlockTemplate.class, timeBlockTemplateDao);
    }
    
    public void clear() {
        appInfoDaoConfig.clearIdentityScope();
        timeBlockDaoConfig.clearIdentityScope();
        timeBlockTemplateDaoConfig.clearIdentityScope();
    }

    public AppInfoDao getAppInfoDao() {
        return appInfoDao;
    }

    public TimeBlockDao getTimeBlockDao() {
        return timeBlockDao;
    }

    public TimeBlockTemplateDao getTimeBlockTemplateDao() {
        return timeBlockTemplateDao;
    }

}
